### ISSUE TITLE
Meta-issue for GSOC 2016

### ISSUE THREAD

**Issue by Gomez** [owncloud/mail#1500]
This is some kind of timeline for the GSOC period:

(Release 0.5?)
- [ ] Take over PR #1446 and finish it. 
- [ ] #625 Integrate account settings better, move from settings section directly to sidebar (mostly done with PR #1446?)
(Release 0.x)
- [ ] #122  Allow sending from aliases
(Release 0.x)
- [ ] #654  Ability to add signature to all messages 
(Release 0.x)

We try to do small steps and release often. Lets move specific discussion into the issue and use this issue for ordering and meta discussion. 

@tahaalibra @ChristophWurst Lets start :P

**Comment by tahaalibra** [comment]
![selection_001](https://cloud.githubusercontent.com/assets/6804341/15771290/511a434a-2987-11e6-91a8-0ff5fbea6fcf.png)

I tried create a mockup for settings (original link:  https://app.moqups.com/tahaalibra@gmail.com/bYGA9cI0/view) 

i think that sidebar was added on OC 8.2, and according to me the new setting page is better option.
i like inputs on this.
@jancborchardt @Gomez @ChristophWurst

**Comment by jancborchardt** [comment]
@tahaalibra heya! :) Some feedback:
- The 3-dot dropdown should be icons with text, as in Files:
![screenshot from 2016-06-03 11-14-31](https://cloud.githubusercontent.com/assets/925062/15774416/6eaf0658-297c-11e6-9a50-8431cb8d2384.png)
- Yep, new settings page sounds good. The sidebar bottom-left part will only have »Add account« for now.
- Very simple and easy aliases list, I like that. We should indeed start out simple here and only have an email input field – every alias should use the name of the main account. We can expand that in the future.
- The signatures, also very good. One question: Is the dropdown necessary? Because the settings are account-specific, so you don’t need to choose the account from a dropdown. It just needs to be a textarea.

Good stuff! :)

**Comment by Gomez** [comment]
Great! A new settings page, like that.

**Comment by tahaalibra** [comment]
@jancborchardt the settings are account specific, which may contain other aliases associated with that account, the dropdown will give an option to choose from the main id and the aliases, this way different signatures can be there for aliases and main id. i hope this makes it clear

**Comment by jancborchardt** [comment]
@tahaalibra right. Makes sense! The default selected option in the dropdown should then be »Signature for all aliases«. :)

**Comment by ChristophWurst** [comment]
> The 3-dot dropdown should be icons with text, as in Files:

As discussed with @tahaalibra, this seems to be a bit harder to implement than it seems, hence I decided we can fix that later.

**Comment by jancborchardt** [comment]
Ok, no problem. Step by step. (Although when there are more actions, it’s important to have text labels because icons themselves are often problematic. And the click/tap area is also larger with added text. :)
